import { defineConfig } from 'vite';
import { resolve, relative, join } from 'path';
import { createHash } from 'crypto';
import fs from 'fs';

// Read package.json to get the version
const packageJson = JSON.parse(fs.readFileSync(resolve(__dirname, 'package.json'), 'utf-8'));
const appVersion = packageJson.version;
const appVersionName = packageJson.version_name;

// Every file under dir, as paths relative to it and with forward slashes.
function listFiles(dir, base = dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = join(dir, entry.name);
    return entry.isDirectory()
      ? listFiles(full, base)
      : [relative(base, full).split(/[\\/]/).join('/')];
  });
}

// Plugin to generate manifest.json with the correct version
function generateManifest() {
  return {
    name: 'generate-manifest',
    generateBundle() {
      const manifestPath = resolve(__dirname, 'public', 'manifest.json');
      const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));

      manifest.version = appVersion;

      this.emitFile({
        type: 'asset',
        fileName: 'manifest.json',
        source: JSON.stringify(manifest, null, 2)
      });
    }
  };
}

// Everything the PWA build has and the extension build does not:
//
//   - the contents of pwa/ (web app manifest, the service worker registration, the
//     bigger icons the install prompt needs), copied verbatim the way public/ is,
//   - a generated sw.js that precaches the whole build so the app opens offline,
//   - the two tags in index.html that pull the first two in,
//   - and NOT public/manifest.json, which is the extension manifest and has no business
//     being served over HTTP.
//
// The service worker DOES call skipWaiting(), and serves the network first.
function generatePwa() {
  const pwaDir = resolve(__dirname, 'pwa');
  const outDir = resolve(__dirname, 'dist_pwa');

  return {
    name: 'generate-pwa',

    transformIndexHtml(html) {
      return html.replace(
        '</head>',
        '  <link rel="manifest" href="./site.webmanifest">\n' +
        '  <script src="./pwa-register.js" defer></script>\n' +
        '</head>'
      );
    },

    closeBundle() {
      // The extension manifest and its background script have no business being served
      // over HTTP; they only land here because public/ is copied wholesale.
      fs.rmSync(join(outDir, 'manifest.json'), { force: true });
      fs.rmSync(join(outDir, 'background.js'), { force: true });

      fs.cpSync(pwaDir, outDir, { recursive: true });

      const assets = listFiles(outDir).sort();

      const digest = createHash('sha1');
      for (const asset of assets) {
        digest.update(asset);
        digest.update(fs.readFileSync(join(outDir, asset)));
      }
      const cacheVersion = `v${appVersion}-${digest.digest('hex').slice(0, 8)}`;

      fs.writeFileSync(join(outDir, 'sw.js'), serviceWorkerSource(cacheVersion, assets));
    }
  };
}

function serviceWorkerSource(cacheVersion, assets) {
  return `// Generated by vite.config.js. Do not edit: it is rewritten on every PWA build.
const PREFIX = 'linkbridge-' + new URL(self.registration.scope).pathname + '-';
const CACHE = PREFIX + '${cacheVersion}';
const ASSETS = ${JSON.stringify(assets, null, 4)};

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE).then((cache) => cache.addAll(
            ASSETS.map((asset) => new Request(asset, { cache: 'reload' }))
        ))
    );
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys()
            .then((names) => Promise.all(
                names.filter((name) => name.startsWith(PREFIX) && name !== CACHE)
                    .map((name) => caches.delete(name))
            ))
            .then(() => self.clients.claim())
    );
});

// ignoreVary is not optional. A server that answers with \`Vary: Origin\` — vite preview does,
// and so do plenty of static hosts — makes the cache miss for every request the browser sends
// in CORS mode, which is exactly what a module script and a @font-face are. The symptom is
// nasty: offline, the stylesheet loads and the app does not.
const MATCH = { ignoreVary: true };

// How long a launch may wait for the network before the cached copy answers instead. 
const NETWORK_TIMEOUT_MS = 1000;

// A hashed name cannot change contents without changing its URL, so the copy in the cache
// IS the copy on the server: no request, no race, nothing to wait for. Everything else can
// change underneath the same URL —index.html, boot.js, the manifest, the icons— and that is
// what the race below is for. Keeps a warm launch down to a couple of requests.
function isHashed(url) {
    return new URL(url).pathname.includes('/assets/');
}

// Network first, cache as the offline fallback and as the answer when the network is too
// slow to be useful. Nothing is written back on the way past: this cache is a snapshot of
// one build, and any change to any file —even an unhashed one— changes the digest in CACHE,
// which brings a new worker that precaches the lot again.
async function respond(request) {
    // A navigation is always the app itself: the address may carry anything (a query
    // string, a deep path behind a rewrite) but what has to be served is index.html.
    const key = request.mode === 'navigate' ? './index.html' : request;

    if (isHashed(request.url)) {
        return (await caches.match(key, MATCH)) || fetch(request);
    }

    // Started before the cache is even consulted, on purpose: the lookup must not delay the
    // request that the whole strategy depends on.
    const network = fetch(request, { cache: 'no-cache' });
    const cached = await caches.match(key, MATCH);

    // Nothing to fall back to, so there is nothing to race either: this one waits.
    if (!cached) return network;

    return Promise.race([
        network.catch(() => cached),
        new Promise((resolve) => setTimeout(() => resolve(cached), NETWORK_TIMEOUT_MS))
    ]);
}

self.addEventListener('fetch', (event) => {
    const request = event.request;

    if (request.method !== 'GET') return;
    if (new URL(request.url).origin !== self.location.origin) return;

    event.respondWith(respond(request));
});
`;
}

export default defineConfig(({ mode }) => {
  const isDebug = mode === 'dev';
  const isPwa = mode === 'pwa';

  return {
    root: 'src',
    base: './',
    build: {
      outDir: isPwa ? '../dist_pwa' : '../dist',
      emptyOutDir: true,
      sourcemap: isDebug,
      rollupOptions: {
        output: {
          entryFileNames: isDebug ? 'assets/[name].js' : 'assets/[name].[hash].js',
          assetFileNames: isDebug ? 'assets/[name].[ext]' : 'assets/[name].[hash].[ext]',
        }
      },
      minify: isDebug ? false : 'esbuild',
    },
    publicDir: '../public',
    plugins: [
      isPwa ? generatePwa() : generateManifest()
    ],
    define: {
      __APP_DEBUG__: JSON.stringify(isDebug),
      __APP_VERSION__: JSON.stringify(appVersion),
      __APP_VERSION_NAME__: JSON.stringify(appVersionName),
    },
  };
});
